//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIDIP_ADO_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public string AdIdentity { get; set; }
        public string AdName { get; set; }
        public System.DateTime AdBrithday { get; set; }
        public System.DateTime AdCreatedDate { get; set; }
        public string AdAccount { get; set; }
        public string AdPassword { get; set; }
        public string AdEmail { get; set; }
    }
}
