//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TIDIP_ADO_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disaster_Accident
    {
        public int DAID { get; set; }
        [Required(ErrorMessage = "地點為必填欄位")]
        public string DALocation { get; set; }

        public string County_City { get; set; }

        public string Area { get; set; }
        public System.DateTime DACreatedDate { get; set; }

        [Required(ErrorMessage = "描述為必填欄位")]
        public string DAMessage { get; set; }
        public int MbIdentity { get; set; }
        public string DATypeID { get; set; }
        public string Member_MbIdentity { get; set; }
    
        public virtual Disaster_Accident_Type Disaster_Accident_Type { get; set; }
        public virtual Members Members { get; set; }
    }
}
