//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIDIP_ADO_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.Disaster_Accident = new HashSet<Disaster_Accident>();
        }
    
        public string MbIdentity { get; set; }
        public string MbName { get; set; }
        public string MbPhone { get; set; }
        public string MbEmail { get; set; }
        public System.DateTime MbBrithday { get; set; }
        public System.DateTime MbCreatedDate { get; set; }
        public string MbAccount { get; set; }
        public string MbPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disaster_Accident> Disaster_Accident { get; set; }
    }
}
