//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIDIP_ADO_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Police
    {
        public int PoliceID { get; set; }
        public string PoliceName { get; set; }
        public string County_City { get; set; }
        public string Area { get; set; }
        public string PoliceAddress { get; set; }
        public System.DateTime PoliceCreatedDate { get; set; }
        public string PoliceTel { get; set; }
    }
}
