//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIDIP_ADO_NET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TIDIPEntities : DbContext
    {
        public TIDIPEntities()
            : base("name=TIDIPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Disaster_Accident> Disaster_Accident { get; set; }
        public virtual DbSet<Disaster_Accident_Type> Disaster_Accident_Type { get; set; }
        public virtual DbSet<Medicals> Medicals { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Police> Police { get; set; }
        public virtual DbSet<Rescues> Rescues { get; set; }
    }
}
